### ISSUE TITLE
add inbound integration

### ISSUE THREAD

**Issue by cgrayson** [activeprospect/leadconduit-integration-lendio#46]
Build an integration that mimics the Lendio system response, which will include passing through a redirect URL in the same format as we receive it from Lendio.

More details about the process that needs to be supported are in [this spreadsheet](https://docs.google.com/spreadsheets/d/1v0TesuwsmboGptGiiBwWflHbC0hw3VCBp-hBgwvTDuw/edit#gid=0).

**Comment by cgrayson** [comment]
Here is an internal copy of the [Lendio posting doc](https://drive.google.com/a/activeprospect.com/file/d/0B3snTzjBrjGRNTNBUThNaUFxNkE/view).

**Comment by ros3bud** [comment]
I'm going to update the description in the integrations priority list to something more like this "the inbound integration should mimic posting to Lendio." There was some confusion as to what was expected for this integration. But after talking with @cgrayson, it has become clear that the integration will be looked at as successful if vendors can simply update their forms to POST to LC rather than Lendio.

**Comment by ros3bud** [comment]
added in 0.2.0
